os: osx
language: node.js
node_js:
  - "7.9.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm i -g npm
  - cd electron && npm install
cache:
  directories:
    - "electron/node_modules"