os: osx
language: node_js
node_js:
  - "10"
env:
  - CXX=g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm i -g npm
  - cd electron && npm install && cd ..
cache:
  directories:
    - "electron/node_modules"