os: osx
language: node_js
node_js:
  - "10"
env:
  - CXX=g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
before_script:
  - npm i -g npm
install:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm install